# === Robot Mindset Setup Assistant === 
# This file is used to configure the setup assistant for the {{ args.package.name | default(package_name) }} package.
# It contains information about the package, capabilities, and launch configurations.

# This YAML file acts as both the template and the data source for generating a final
# configuration. It uses Jinja2 syntax (e.g., {{ args.package.name | default(package_name) }}) to allow referencing
# values defined earlier in the file.
# The file is first loaded as a dictionary using yaml.safe_load(), then passed to a
# Jinja2 template created from the same file. The template is rendered with this dictionary
# as context, and the result is parsed again into the final YAML structure.

package:
  name: test_pkg
  description: A package to examine the test_pgk.
  version: "0.0.1"
  maintainer: Robot Mindset
  maintainer_email: robot.mindset@robot-mindset.com
  license:
    value: MIT
    options: [BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3]
  language: cpp # python, cpp
  environment: ros.noetic # ros.noetic, ros.humble, (debian)
  dependencies:
    apt:
      - python3-catkin-tools
      - libspdlog-dev
    pip: []
    ros:
      - std_msgs
      - roscpp
    git: []
      # - name: sim2real_gap
      #   url: https://gitlab.cc-asp.fraunhofer.de/multirobot/strategy/sim2real_gap.git
      #   version: main
    packages: # CMakeLists.txt modifications
      - name: spdlog # https://github.com/gabime/spdlog
        target_link: spdlog::spdlog

interfaces: 
  ros:
    topics:
      publisher:
        - name: "interface_topic_float_out"
          msgs: "std_msgs/Float64"
          description: "A ROS Topic interface."
        - name: "interface_topic_string_out"
          msgs: "std_msgs/String"
          description: "A string interface."
      subscriber:
        - name: "interface_topic_float_in"
          msgs: "std_msgs/Float64"
          description: "A ROS Topic interface."
        - name: "interface_topic_string_in"
          msgs: "std_msgs/String"
          description: "A string interface."
    services:
      server:
        - name: "set_controller_sate"
          msgs: "std_srvs/SetBool"
          description: "A service interface."
      client:
        - name: "get_controller_state"
          msgs: "std_srvs/SetBool"
          description: "A service interface."
    actions:
      server:
        - name: "action_interface"
          msgs: "my_msgs/action_conig"
          description: "An action interface for the robot."
      client:
        - name: "action_interface_client"
          msgs: "my_msgs/action_conig"
          description: "An action interface for the robot."
  urdf: 
    parent:
      name: "parent"
      description: "The parent link of the robot."
      xyz: "0 0 0"
      rpy: "0 0 0"
    childs:
      - name: "gripper"
        description: "The first child link of the robot."
        parent: "parent_link"
        xyz: "0 0 0"
        rpy: "0 0 0"
      - name: "sensor"
        parent: "parent_link"
        description: "The second child link of the robot."
        xyz: "0 0 0"
        rpy: "0 0 0"

spark:
  capabilities:
    - type: "data_processing"

link_serve:
  interfaces:
    - direction: "in"
      type: "topic"
      msgs: "sensor_msgs/JointState"
      description: "Robot joint states."
    - direction: "out"
      type: "topic"
      msgs: "sensor_msgs/JointState"
      description: "Combined joint states"

single_serve:
  # Todo: eher Beschreibung für ein Projekt / diese Beschreibung sollte gleich sein für Packagete und Projekte / oder diese Beschreibung braucht man nicht, da alle multi_serve Packete auch als single_serve laufen können
  # name: robot_state_publisher
  #
  # mtc_generator: true
  # moveit: true
  # robot_state_publisher: true

multi_serve:
  # launch:
  #   arguements:
  #     - name: "instance_config_folder"
  #       description: "Location of the instance config folder."
  #       default: "$(find {{ args.package.name }})/example/instance_config"

    