#!/bin/bash
# WARNING: This file was auto-generated by dev-setup/setup.py.


# # ------- base -------
# # Build the base image
# # -------------------------
# docker build --file .dev-setup/docker/Dockerfile.base \
#     --secret id=gitcreds,src=$HOME/.git-credentials \
#     --tag robot_mindset_setup_assistant:base-1.0 \
#     .
# docker tag robot_mindset_setup_assistant:base-1.0 container-registry.gitlab.cc-asp.fraunhofer.de/multirobot/robot_mindset_setup_assistant:base-1.0


# # ------- ci -------
# # Build the ci image
# # -------------------------
# docker build --file .dev-setup/docker/Dockerfile.ci \
#     --secret id=gitcreds,src=$HOME/.git-credentials \
#     --tag robot_mindset_setup_assistant:ci-1.0 \
#     .
# docker tag robot_mindset_setup_assistant:ci-1.0 container-registry.gitlab.cc-asp.fraunhofer.de/multirobot/robot_mindset_setup_assistant:ci-1.0

# ------- run -------
# Build the run image
# -------------------------
docker build --file .dev-setup/docker/Dockerfile.run \
    --secret id=gitcreds,src=$HOME/.git-credentials \
    --tag robot_mindset_setup_assistant:run-1.0 \
    .
