#!/bin/bash
# -----------------------------------------------------------------------------
# WARNING: This file was auto-generated by dev-setup/setup.py. 
# Do not edit directly; modify the template or input variables instead.
# -----------------------------------------------------------------------------

# set -e