# === Robot Mindset Setup Assistant === 
# This file is used to configure the setup assistant for the robot_ur package.
# It contains information about the package, capabilities, and launch configurations.

package:
  name: "robot_ur"
  description: "A package for serving a UR robot."

spark:
  capabilities:
    - type: "robot"
  interfaces:
    - name: "interface_topic_string_in"
      direction: "in"
      msgs: "std_msgs/String"
      type: "topic"
      description: "A string interface for the robot."
    - name: "set_conroller"
      direction: "in"
      msgs: "std_msgs/String"
      type: "topic"
      description: "A string interface for the robot."

link:
  joint_state_publisher: 
    topic: "joint_states"

single:
  moveit: true
  robot_state_publisher: true

launch:
  default_for_all:
    arguments:
      - name: "namespace"
        description: "Namespace for the drink server."
        default: "drink_server"
      - name: "simulation"
        description: "Flag to start the application as a simulation or not."
        default: "false"
      - name: "simulation_with_gazebo"
        description: "Flag to start the application with Gazebo simulation. If simulation is false, this will be ignored."
        default: "false"
  
  single_serve:
    arguments:
      - name: "ur_type"
        description: "Possible robot type values: ur3, ur3e, ur5, ur5e, ur10, ur10e, ur16e, ur20"
        default: "ur10e"
  
  multi_serve:
    arguments:
      - name: "instance_config_folder"
        description: "Location of the instance config folder."
        default: "$(find robot_ur)/instance_config"
      - name: "robot_description_path"
        description: "Path to the robot description file."
        default: "$(find robot_ur)/urdf/example.xacro"
      - name: "gazebo_spawn_args"
        description: "Arguments for spawning the robot in Gazebo."
        default: "-model robot_ur -unpause
                -J robot_ur_elbow_joint 2         -J robot_ur_shoulder_lift_joint -2    -J robot_ur_shoulder_pan_joint 0
                -J robot_ur_wrist_1_joint -0.85   -J robot_ur_wrist_2_joint -1.57       -J robot_ur_wrist_3_joint 0"
      - name: "controller_config_file"
        description: "Path to the controller configuration file."
        default: "$(find instance_config_folder)/controller_config.yaml"
      - name: "controllers"
        description: "List of controllers to load."
        default: "joint_state_controller pos_joint_traj_controller"
      - name: "stopped_controllers"
        description: "List of controllers to stop."
        default: "joint_group_vel_controller speed_scaling_state_controller"

  link_serve:
    arguments:
      - name: "joint_state_publisher_source_list"
        description: "List of joint state publishers."
        default: "[robot_ur/joint_states]"
    